<?php
/**
 * Created by JetBrains PhpStorm.
 * User: nhan
 * Date: 1/15/15
 * Time: 7:53 AM
 * To change this template use File | Settings | File Templates.
 */

function merc_global_menu()
{
    $items['admin/portal/dashboard'] = array(
        'title' => 'Admin Dashboard',
        'page callback' => 'merc_global_admin_dashboard',
        'access arguments' => array('admin dashboard'),
        'type' => MENU_LOCAL_ACTION,
        'weight' => 1,
    );


    return $items;
}

function merc_global_permission() {
    return array(
        'admin dashboard' => array(
            'title' => t('Administer dashboard'),
            'description' => t('Perform administration tasks for my module.'),
        ),
    );
}


/**
 * Implement hook_block
 */
function merc_global_block_info() {

    $blocks['merc_global_category_list'] = array(
        'info' => t('Merc category list'),
    );
    $blocks['merc_global_brand_list'] = array(
        'info' => t('Merc brand list'),
    );
    $blocks['merc_global_order'] = array(
        'info' => t('Merc order form'),
    );
    $blocks['merc_global_bg_form'] = array(
        'info' => t('Merc bg form'),
    );
    $blocks['merc_global_cart'] = array(
        'info' => t('Merc cart'),
    );
    $blocks['merc_global_user'] = array(
        'info' => t('Merc User'),
    );
    $blocks['merc_global_wishlist'] = array(
        'info' => t('Merc Wishlist'),
    );
    $blocks['merc_admin_panel'] = array(
        'info' => t('Admin Panel'),
    );
    return $blocks;
}

/*
 * Hook Block View
 */
function merc_global_block_view($delta = '') {
    $block = array();

    switch($delta) {
        case 'merc_global_category_list':
            $block['subject'] = '';
            $block['content'] = merc_global_category_list();
            break;
        case 'merc_global_brand_list':
            $block['subject'] = '';
            $block['content'] = merc_global_brand_list();
            break;
        case 'merc_global_order':
            $block['subject'] = '';
            $block['content'] = merc_global_order();
            break;
        case 'merc_global_cart':
            $block['subject'] = '';
            $block['content'] = merc_global_cart();
            break;
        case 'merc_global_user':
            $block['subject'] = '';
            $block['content'] = merc_global_user();
            break;
        case 'merc_global_wishlist':
            $block['subject'] = '';
            $block['content'] = merc_global_wishlist();
            break;
        case 'merc_admin_panel':
            $block['subject'] = 'Admin Panel';
            $block['content'] = merc_global_admin_dashboard();
            break;
    }
    return $block;
}
/*
 * Category list
 */
function merc_global_category_list(){
    $terms = false;
    if(arg(0)=='taxonomy' && arg(1)=='term' && arg(3) == Null){
        $tid = arg(2);
        $term = taxonomy_term_load($tid);
        $child = taxonomy_get_children($tid);
        if($child){
            $terms = $child;
            $parent_name = $term->name;
        }else{
            $parent = taxonomy_get_parents($tid);
            foreach($parent as $pa){
                $terms = taxonomy_get_children($pa->tid);
                $parent_name = $pa->name;
            }
        }

    }
    ;
    if($node = menu_get_object('node')){
        $tid = $node->field_category[LANGUAGE_NONE][0]['tid'];
        $term = taxonomy_term_load($tid);
        $child = taxonomy_get_children($tid);

        if($child){
            $terms = $child;
            $parent_name = $term->name;
        }else{
            $parent = taxonomy_get_parents($tid);
            foreach($parent as $pa){
                $terms = taxonomy_get_children($pa->tid);
                $parent_name = $pa->name;
            }
        }

    }
    if($terms){

        $output = '';
        $output .='<h2 class="title">'.$parent_name.'</h2>';
        $output .='<ul class="sub-category">';
        foreach($terms as $t){
            $term = taxonomy_term_load($t->tid);
            if($_GET['q']==menu_tree_set_path($term->name,'taxonomy/term/'.$term->tid)){
                $output .='<li class="active">'.l($term->name,'taxonomy/term/'.$term->tid).'</li>';
            }else{
                $output .='<li>'.l($term->name,'taxonomy/term/'.$term->tid).'</li>';
            }


        }
        $output .='</ul>';
        return $output;

    }else{
        return false;
    }
//    $voca = taxonomy_vocabulary_machine_name_load('category');
//    $terms = taxonomy_get_tree($voca->vid);
//    $output = '';
//    $output .='<div class="category-list-wrapper">';
//    foreach($terms as $term){
//       if($term->parents[0]==0){
//           $output .= '<h2 class="block-title">'.$term->name.'</h2>';
//           $children = taxonomy_get_children($term->tid);
//           $output .= "<ul>";
//           foreach($children as $child){
//               $term_child = taxonomy_term_load($child->tid);
//               $output .='<li class="cate-item">'.l($term_child->name,'taxonomy/term/'.$term_child->tid).'</li>';
//
//           }
//           $output .='</ul>';
//       }
//    }
//
//    $output .='</div>';
//    return $output;
}
/*
 * Brand list
 */
function merc_global_brand_list(){
    $voca = taxonomy_vocabulary_machine_name_load('product');
    $terms = taxonomy_get_tree($voca->vid);
    $output = '';
    $output .='<div class="brands-list-wrapper">';
    $class= '';
    foreach($terms as $term){
        if($term->parents[0]==0){
            if(arg(1) == $term->tid){
                $output .= '<h2 class="block-title active">'.l($term->name,'brand/'.$term->tid).'</h2>';
            }else{
                $output .= '<h2 class="block-title ">'.l($term->name,'brand/'.$term->tid).'</h2>';
            }

        }
    }

    $output .='</div>';
    return $output;
}

/*
 * Order webform
 */
function merc_global_order(){
    $node = node_load(162);
    $form =  drupal_get_form('webform_client_form_162',$node,array());
    return $form;

}

/*
 * Implement hook_form_alter
 */

function merc_global_form_alter(&$form, &$form_state, $form_id){
    switch($form_id){
        case 'user_register_form':
            if(arg(0) != 'admin'){
                $form['account']['name']['#title'] = 'Tên tài khoản';
                $form['account']['mail']['#title'] = 'Địa chỉ email';
                $form['actions']['submit']['#value'] = 'Tạo tài khoản';
            }

            drupal_set_title('Đăng ký tài khoản');
            break;
        case 'user_login':
            $form['name']['#title'] = 'Tên tài khoản';
            $form['pass']['#title'] = 'Mật khẩu';
            $form['actions']['submit']['#value'] = 'Đăng nhập';
            drupal_set_title('Đăng nhập ');
            break;
        case 'user_pass':
            $form['name']['#title'] = 'Tên tài khoản hoặc địa chỉ email';
            $form['actions']['submit']['#value'] = 'Tìm mật khẩu ';
            drupal_set_title('Quên mật khẩu  ');
            break;
        case 'user_profile_form':
            $form['account']['mail']['#title'] = 'Địa chỉ email';
            $form['account']['current_pass']['#title'] = 'Mật khẩu hiện tại ';
            $form['actions']['submit']['#value'] = 'Cập nhật ';
            break;

    }
}


/*
 * Implement hook_theme
 */

function merc_global_theme() {
    return array(
        'merc_global_panel' => array(
            'render element' => 'element',
            'template' => 'theme/merc-global-panel',
        ),

    );
}

function merc_global_admin_dashboard(){
    global $user;
    drupal_add_css(drupal_get_path('module','merc_global').'/admin_panel/admin-panel.css');
    return array('#theme' => 'merc_global_panel');
}

/*
 * cart
 */
function merc_global_cart(){
    global $user;
    $order = commerce_cart_order_load($user->uid);
    $output = '';
    if($order){
        $wrapper = entity_metadata_wrapper('commerce_order', $order);
        $line_items = $wrapper->commerce_line_items;
        $quantity = commerce_line_items_quantity($line_items, commerce_product_line_item_types());
        $order_total = $wrapper->commerce_order_total->value();
        $output = '';
        if($quantity > 0){
            $output .= '<a href="/cart"><div class="cart-wrapper"><b>Giỏ hàng:</b> '.commerce_currency_format($order_total['amount'], $order_total['currency_code']).' ('.$quantity.')'.'</div></a>';
        }else{
            $output .= '<div class="cart-wrapper"><b>Giỏ hàng:</b> 0đ (0)'.'</div>';
        }


    }else{
        $output .= '<div class="cart-wrapper"><b>Giỏ hàng:</b> 0đ (0)'.'</div>';
    }
    return $output;
}

/*
 * User block
 */

function merc_global_user(){
    global $user;
    $output = '';
    if($user->uid > 0){
       $output .='<div class="user-wrapper">Hello '.l($user->name,'user/'.$user->uid.'/edit').' | '.l('Đăng xuất','user/logout').'</div>';
    }else{
        $output .='<div class="user-wrapper">'.l('Đăng nhập','user/login').' | '.l('Đăng ký','user/register').'</div>';
    }
    return $output;
}

/*
 * Wishlist
 */
function merc_global_wishlist(){
    global $user;
    $output = '';
    if($user->uid > 0){
        $output .='<div class="user-wishlist">'.l('Sản phẩm yêu thích','user/'.$user->uid.'/wishlist').'</div>';
    }else{
        $output .='<div class="user-wishlist">'.l('Sản phẩm yêu thích','user/login').'</div>';
    }
    return $output;
}

//
//function merc_global_preprocess_page(&$variables){
//    $url = $_GET['q'];
//    $url = explode('/',$url);
//    if($url[0] == 'new'){
//        $term = taxonomy_term_load($url[1]);
//        drupal_set_title('Tin tức  »  '.$term->name);
//    }
//}